/** File page actions */
export const FILE_PAGE_INIT = 'FILE_PAGE_INIT'

export const GET_FILE_DETAILS_REQUEST = 'GET_FILE_DETAILS_REQUEST'
export const GET_FILE_DETAILS_REQUEST_SUCCESS = 'GET_FILE_DETAILS_REQUEST_SUCCESS'
export const GET_FILE_DETAILS_REQUEST_FAILURE = 'GET_FILE_DETAILS_REQUEST_FAILURE'

export const GET_FILE_TAGS_REQUEST = 'GET_FILE_TAGS_REQUEST'
export const GET_FILE_TAGS_REQUEST_SUCCESS = 'GET_FILE_TAGS_REQUEST_SUCCESS'
export const GET_FILE_TAGS_REQUEST_FAILURE = 'GET_FILE_TAGS_REQUEST_FAILURE'

/** Lines */
export const FEEDBACK_LINE_REQUEST = 'FEEDBACK_LINE_REQUEST'
export const FEEDBACK_LINE_SUCCESS = 'FEEDBACK_LINE_SUCCESS'
export const FEEDBACK_LINE_FAILURE = 'FEEDBACK_LINE_FAILURE'

export const ON_LINE_ITEM_SELECT = 'ON_LINE_ITEM_SELECT'
export const CLEAR_SELECT_LINES = 'CLEAR_SELECT_LINES'

/** Tags */
export const TAGS_COLLAPSE = 'TAGS_COLLAPSE'
export const ON_TAG_CLICK = 'ON_TAG_CLICK'

/** Trails */
export const ADD_TO_TRAILS_CHECKOUT = 'ADD_TO_TRAILS_CHECKOUT'
export const UPDATE_REORDERED_LIST_OF_TRAILS = 'UPDATE_REORDERED_LIST_OF_TRAILS'
export const TOGGLE_ADD_NEW_TRAIL_LINE_ICON = 'TOGGLE_ADD_NEW_TRAIL_LINE_ICON'

/** Filters */
export const FILTER_APPLIED = 'FILTER_APPLIED'
export const FILTERS_COLLAPSE = 'FILTERS_COLLAPSE'
export const SHOW_READ_LINES = 'SHOW_READ_LINES'
export const SHOW_ALL_LINES = 'SHOW_ALL_LINES'
export const SHOW_UNREAD_LINES = 'SHOW_UNREAD_LINES'
export const SORT_AND_ARRANGE_LINES_BY = 'SORT_AND_ARRANGE_LINES_BY'

/** Users */
export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST'
export const GET_USER_DETAILS_REQUEST_SUCCESS = 'GET_USER_DETAILS_REQUEST_SUCCESS'
export const GET_USER_DETAILS_REQUEST_FAILURE = 'GET_USER_DETAILS_REQUEST_FAILURE'

/** Search query a.k.a query */
export const SEARCH_QUERY_REQUEST = 'SEARCH_QUERY_REQUEST'
export const SEARCH_QUERY_REQUEST_SUCCESS = 'SEARCH_QUERY_REQUEST_SUCCESS'
export const SEARCH_QUERY_REQUEST_FAILURE = 'SEARCH_QUERY_REQUEST_FAILURE'
