/** File page actions */
export const ON_FILE_PAGE_INIT = 'ON_FILE_PAGE_INIT'

export const GET_FILE_DETAILS_REQUEST = 'GET_FILE_DETAILS_REQUEST'
export const GET_FILE_DETAILS_REQUEST_SUCCESS = 'GET_FILE_DETAILS_REQUEST_SUCCESS'
export const GET_FILE_DETAILS_REQUEST_FAILURE = 'GET_FILE_DETAILS_REQUEST_FAILURE'

/** Filters */


/** Search query a.k.a query */
export const SEARCH_QUERY_REQUEST = 'SEARCH_QUERY_REQUEST'
export const SEARCH_QUERY_REQUEST_SUCCESS = 'SEARCH_QUERY_REQUEST_SUCCESS'
export const SEARCH_QUERY_REQUEST_FAILURE = 'SEARCH_QUERY_REQUEST_FAILURE'
