/** File page actions */
export const FILE_PAGE_INIT = 'FILE_PAGE_INIT'

export const GET_FILE_DETAILS_REQUEST = 'GET_FILE_DETAILS_REQUEST'
export const GET_FILE_DETAILS_REQUEST_SUCCESS = 'GET_FILE_DETAILS_REQUEST_SUCCESS'
export const GET_FILE_DETAILS_REQUEST_FAILURE = 'GET_FILE_DETAILS_REQUEST_FAILURE'

export const GET_FILE_TAGS_REQUEST = 'GET_FILE_TAGS_REQUEST'
export const GET_FILE_TAGS_REQUEST_SUCCESS = 'GET_FILE_TAGS_REQUEST_SUCCESS'
export const GET_FILE_TAGS_REQUEST_FAILURE = 'GET_FILE_TAGS_REQUEST_FAILURE'

/** Lines */
export const LIKE_LINE_REQUEST = 'LIKE_LINE_REQUEST'
export const LIKE_LINE_SUCCESS = 'LIKE_LINE_SUCCESS'
export const LIKE_LINE_FAILURE = 'LIKE_LINE_FAILURE'

export const DISLIKE_LINE_REQUEST = 'DISLIKE_LINE_REQUEST'
export const DISLIKE_LINE_SUCCESS = 'DISLIKE_LINE_SUCCESS'
export const DISLIKE_LINE_FAILURE = 'DISLIKE_LINE_FAILURE'

/** Tags */
export const TAGS_COLLAPSE = 'TAGS_COLLAPSE'
export const ON_TAG_CLICK = 'ON_TAG_CLICK'

/** Filters */
export const FILTER_APPLIED = 'FILTER_APPLIED'
export const FILTERS_COLLAPSE = 'FILTERS_COLLAPSE'
export const SHOW_READ_LINES = 'SHOW_READ_LINES'
export const SHOW_ALL_LINES = 'SHOW_ALL_LINES'
export const SHOW_UNREAD_LINES = 'SHOW_UNREAD_LINES'
export const SORT_AND_ARRANGE_LINES_BY = 'SORT_AND_ARRANGE_LINES_BY'

/** Users */
export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST'
export const GET_USER_DETAILS_REQUEST_SUCCESS = 'GET_USER_DETAILS_REQUEST_SUCCESS'
export const GET_USER_DETAILS_REQUEST_FAILURE = 'GET_USER_DETAILS_REQUEST_FAILURE'

/** Search query a.k.a query */
export const SEARCH_QUERY_REQUEST = 'SEARCH_QUERY_REQUEST'
export const SEARCH_QUERY_REQUEST_SUCCESS = 'SEARCH_QUERY_REQUEST_SUCCESS'
export const SEARCH_QUERY_REQUEST_FAILURE = 'SEARCH_QUERY_REQUEST_FAILURE'
